#!/bin/sh

# Send a notification if the laptop battery is either low or is fully charged.
# Set on a systemd timer (~/.config/systemd/user/battery-alert.timer).

export DISPLAY=:0
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"

# loop every 5minute
while true; do
# Battery percentage at which to notify
WARNING_LEVEL=20
CRITICAL_LEVEL=5
BATTERY_DISCHARGING=$(upower -d | grep "state" | head -n 1 | grep -c "discharging")
BATTERY_LEVEL=$(upower -d | grep "percentage" | grep -P -o '[0-9]+(?=%)' | head -n 1)

# Use files to store whether we've shown a notification or not (to prevent multiple notifications)
FULL_FILE=/tmp/batteryfull
EMPTY_FILE=/tmp/batteryempty
CRITICAL_FILE=/tmp/batterycritical

CHARGING_FILE="/tmp/batterycharging"
DISCHARGING_FILE="/tmp/batterydischarging"

# Reset notifications if the computer is charging/discharging
if [ "$BATTERY_DISCHARGING" -eq 1 ] && [ -f $FULL_FILE ]; then
	rm $FULL_FILE
elif [ "$BATTERY_DISCHARGING" -eq 0 ] && [ -f $EMPTY_FILE ]; then
	rm $EMPTY_FILE
fi

if [ "$BATTERY_DISCHARGING" -eq 1 ] && [ -f $CHARGING_FILE ]; then
    rm $CHARGING_FILE
elif [ "$BATTERY_DISCHARGING" -eq 0 ] && [ -f $DISCHARGING_FILE ]; then
    rm $DISCHARGING_FILE
fi


# If the battery is charging and is full (and has not shown notification yet)
if [ "$BATTERY_LEVEL" -gt 99 ] && [ "$BATTERY_DISCHARGING" -eq 0 ] && [ ! -f $FULL_FILE ]; then
    ICON="battery-full-charging"
	notify-send "Battery Charged" "Battery is fully charged." -i "$ICON" -r 9991
	touch $FULL_FILE
	# If the battery is low and is not charging (and has not shown notification yet)
elif [ "$BATTERY_LEVEL" -le $WARNING_LEVEL ] && [ "$BATTERY_DISCHARGING" -eq 1 ] && [ ! -f $EMPTY_FILE ]; then
    ICON="battery-low"
	notify-send "Low Battery" "${BATTERY_LEVEL}% of battery remaining." -u critical -i "$ICON" -r 9991
	touch $EMPTY_FILE
	# If the battery is critical and is not charging (and has not shown notification yet)
elif [ "$BATTERY_LEVEL" -le $CRITICAL_LEVEL ] && [ "$BATTERY_DISCHARGING" -eq 1 ] && [ ! -f $CRITICAL_FILE ]; then
    ICON="battery-caution"
	notify-send "Battery Critical" "The computer will shutdown soon." -u critical -i "$ICON" -r 9991
	touch $CRITICAL_FILE
fi


#BATTERY STATE
if [ "$BATTERY_DISCHARGING" -eq 0 ] && [ ! -f $CHARGING_FILE ]; then
    ICON="battery"
    notify-send "Charging" "Power is plugged in" --transient -u low -i "$ICON" -r 9991
    touch $CHARGING_FILE
elif [ "$BATTERY_CHARGING" -eq 1 ] && [ ! -f $DISCHARGING_FILE ]; then
    touch $DISCHARGING_FILE
fi


sleep 5
done
