#!/bin/sh

# Increment, decrement, or mute the volume using Pipewire and send a notification

case $1 in
	--up)
		# Set the volume on (if it was muted)
		wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
		wpctl set-volume -l 2.0 @DEFAULT_AUDIO_SINK@ 5%+
		;;
	--down)
		wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
		wpctl set-volume -l 2.0 @DEFAULT_AUDIO_SINK@ 5%-
		;;
	mute)
		wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
		;;
esac

VOLUME=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | tr -dc '0-9' | sed 's/^0\{1,2\}//')


send_notification() {
	if [ "$VOLUME" -lt 33 ]; then 
        ICON="audio-volume-low"
    elif [ "$VOLUME" -lt 66 ]; then 
        ICON="audio-volume-medium" 
    else
        ICON="audio-volume-high"
    fi
	TEXT="Currently at ${VOLUME}%"
	INTVAL="-h int:value:"$VOLUME""

	notify-send \
      --hint=string:x-dunst-stack-tag:wallpaper \
      --hint=string:synchronous:wallpaper \
      "$@" --urgency=low --transient -a "Volume" $INTVAL -i "$ICON" "Volume" "$TEXT" -t 2000 -r 9903
}
mute_notification(){
    TEXT="Muted"
    ICON="audio-volume-muted"
    notify-send \
      --hint=string:x-dunst-stack-tag:wallpaper \
      --hint=string:synchronous:wallpaper \
      "$@" --urgency=low --transient "Volume" "$TEXT" -i "$ICON" -t 2000 -r 9903
}

case $1 in
	mute)
        status=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $3}')
		case $status in
			*MUTED* ) mute_notification;;
			*       ) send_notification;;
		esac;;
	*)
		send_notification;;
esac
